{
 "title": "SN-ALERTS",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Elasticsearch", "query": "elasticsearch" }
  ]
 },
 "panels": [
  {
   "title": "SN-Alert-GeoMap",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "num" } },
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "geoip.location",
       "id": "3",
       "settings": { "precision": 3 },
       "type": "geohash_grid"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "event_type:alert",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-Alert-ByExtraInfoType",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "id": "6",
       "query": "*",
       "settings": {
        "filters": [
         { "label": "SSH-Alert", "query": "_exists_:ssh" },
         { "label": "SMTP-Alert", "query": "_exists_:smtp" },
         { "label": "HTTP-Alert", "query": "_exists_:http" },
         { "label": "TLS-Alert", "query": "_exists_:tls" },
         { "label": "SMB-Alert", "query": "_exists_:smb" },
         { "label": "DNS-Alert", "query": "_exists_:dns" },
         {
          "label": "Other-Alert",
          "query": "-_exists_:ssh -_exists_:smtp -_exists_:http -_exists_:tls -_exists_:dns -_exists_:smb"
         }
        ]
       },
       "type": "filters"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "event_type:alert",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-Alert-Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "event_type:alert",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-Alert-ByVLANIDTop20",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "vlan",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "event_type: alert AND vlan:*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-Alert-Top100Signatures",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "alert.signature.keyword",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "100" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-Alert-ByHttpMethod",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "http.http_method.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "http.http_method:* AND event_type: alert",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-Alert-Proto",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "proto.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "event_type: alert",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-Alert-Top20SrcIP",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "src_ip.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "event_type: alert",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-Alert-Top20SrcPorts",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "src_port",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "event_type: alert",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-Alert-Top20DstIP",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "dest_ip.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "event_type: alert",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-Alert-Top20DstPorts",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "dest_port",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "event_type: alert",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-Alert-ByTlsIssuerdn",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tls.issuerdn.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "event_type: alert",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-Alert-BySmtpHello",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "smtp.helo.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "event_type: alert",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-Alert-ByTlsSni",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tls.sni.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "event_type: alert",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-ThreatHunt-ALERTS-Top100Signatures",
   "type": "table",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "alert.signature.keyword",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "100" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-ThreatHunt-ALERTS-MutlipleUniqueAlertOnDestIP",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "dest_ip.keyword",
       "id": "8",
       "settings": {
        "min_doc_count": "0",
        "missing": null,
        "order": "desc",
        "orderBy": "1",
        "size": "100"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "alert.signature.keyword",
       "id": "1",
       "meta": {},
       "settings": {
        "missing": null,
        "precision_threshold": null
       },
       "type": "cardinality"
      }
     ],
     "query": "*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-ThreatHunt-ALERTS-MutlipleUniqueAlertOnSrcIP",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "src_ip.keyword",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "alert.signature.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-Alert-ByExtraInfoType",
   "type": "table",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select metric",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "select metric" }
       ],
       "settings": {},
       "type": "logs"
      }
     ],
     "query": "event_type:alert",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}