{
 "title": "SN-ALL",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Elasticsearch", "query": "elasticsearch" }
  ]
 },
 "panels": [
  {
   "title": "SN-Alert-ByExtraInfoType",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "event_type.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "30" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "30m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-Alert-Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "event_type:alert",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-Alert-ByExtraInfoType",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:8030",
       "fake": true,
       "id": "6",
       "query": "*",
       "settings": {
        "filters": [
         { "label": "SSH-Alert", "query": "_exists_:ssh" },
         { "label": "SMTP-Alert", "query": "_exists_:smtp" },
         { "label": "HTTP-Alert", "query": "_exists_:http" },
         { "label": "TLS-Alert", "query": "_exists_:tls" },
         { "label": "SMB-Alert", "query": "_exists_:smb" },
         { "label": "DNS-Alert", "query": "_exists_:dns" },
         {
          "label": "Other-Alert",
          "query": "-_exists_:ssh -_exists_:smtp -_exists_:http -_exists_:tls -_exists_:dns -_exists_:smb"
         }
        ]
       },
       "type": "filters"
      },
      {
       "$$hashKey": "object:8031",
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:8028",
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "event_type:alert",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-FILE-EventsOverTime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "30m", "min_doc_count": "0", "offset": "", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "event_type: fileinfo",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-ThreatHunt-ALERTS-Top100Signatures",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "alert.signature.keyword",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "100" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-Proto-app_proto",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "app_proto.keyword",
       "id": "5",
       "settings": { "min_doc_count": 0, "order": "asc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "proto.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-DNS-DnsOverTime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "id": "4",
       "query": "*",
       "settings": {
        "filters": [
         { "query": "event_type: dns" }
        ]
       },
       "type": "filters"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "30m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "event_type: dns",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-SMTP-SmtpOverTime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "id": "4",
       "query": "*",
       "settings": {
        "filters": [
         { "query": "event_type: smtp" }
        ]
       },
       "type": "filters"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "30m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "event_type: smtp",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-TLS-EventsOverTime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "id": "4",
       "query": "*",
       "settings": {
        "filters": [
         { "query": "event_type: tls" }
        ]
       },
       "type": "filters"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "30m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "event_type: tls",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-SSH-EventsOverTime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "id": "4",
       "query": "*",
       "settings": {
        "filters": [
         { "query": "event_type: ssh" }
        ]
       },
       "type": "filters"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "30m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "event_type: ssh",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-ALL-EventsList",
   "type": "table",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select metric",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "select metric" }
       ],
       "settings": {},
       "type": "logs"
      }
     ],
     "query": "NOT event_type:stats AND event_type:*",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}