{
 "title": "SN-FILE-Transactions",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "elasticsearch", "query": "elasticsearch" }
  ]
 },
 "panels": [
  {
   "title": "SN-FILE-Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "logstash-fileinfo-*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-FILE-GeoIPPDFAndExecutables",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "num" } },
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "geoip.location",
       "id": "3",
       "settings": { "precision": 3 },
       "type": "geohash_grid"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "logstash-fileinfo-* fileinfo.magic: \"PDF\" OR fileinfo.magic: \"executable\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-FILE-ByTypeOverTime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "fileinfo.type.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "30m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "logstash-fileinfo-*  event_type: fileinfo",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-FILE-ByHTTPByHostnameServed",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "http.hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "logstash-fileinfo-*  event_type: fileinfo",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-FILE-ByAppProto",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "app_proto.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "logstash-fileinfo-*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-FILE-Top20SrcIP",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "src_ip.keyword",
       "id": "8",
       "settings": {
        "min_doc_count": "1",
        "missing": null,
        "order": "desc",
        "orderBy": "_count",
        "size": "20"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "alert.signature.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "logstash-fileinfo-* event_type: fileinfo",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-FILE-Top20DestIP",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:10749",
       "fake": true,
       "field": "dest_ip.keyword",
       "id": "8",
       "settings": {
        "min_doc_count": "1",
        "missing": null,
        "order": "desc",
        "orderBy": "_count",
        "size": "20"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:10747",
       "field": "alert.signature.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "logstash-fileinfo-* event_type: fileinfo",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-FILE-Top20SrcPort",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "src_port",
       "id": "8",
       "settings": {
        "min_doc_count": "1",
        "missing": null,
        "order": "desc",
        "orderBy": "_count",
        "size": "20"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "alert.signature.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "logstash-fileinfo-* event_type: fileinfo",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-FILE-Top20DestPort",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "dest_port",
       "id": "8",
       "settings": {
        "min_doc_count": "1",
        "missing": null,
        "order": "desc",
        "orderBy": "_count",
        "size": "20"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "alert.signature.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "logstash-fileinfo-* event_type: fileinfo",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-FILE-EventsList",
   "type": "table",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select metric",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "select metric" }
       ],
       "settings": {},
       "type": "logs"
      }
     ],
     "query": "logstash-fileinfo-* event_type:fileinfo",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}