{
 "title": "SN-FLOW",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "elasticsearch", "query": "elasticsearch" }
  ]
 },
 "panels": [
  {
   "title": "SN-Application protocol",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "app_proto.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "5" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": {
        "interval": "30m",
        "min_doc_count": 0,
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "logstash-*  event_type:flow",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-Flow unique count of src and dst IP",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:10874",
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "30m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:10870",
       "field": "dest_ip.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      },
      {
       "$$hashKey": "object:10871",
       "field": "src_ip.keyword",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "logstash-*  NOT event_type:stats AND event_type:*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-Mean flow age and count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "30m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "flow.age",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "logstash-*  event_type:flow",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-FLOW-EventsList",
   "type": "table",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select metric",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "select metric" }
       ],
       "settings": {},
       "type": "logs"
      }
     ],
     "query": "logstash-flow-*",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}