{
 "title": "SN-HTTP",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "elasticsearch", "query": "elasticsearch" }
  ]
 },
 "panels": [
  {
   "title": "SN-HTTP-Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:11162",
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:11160",
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "logstash-http-* AND event_type:http",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-HTTP-GeoIP",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "num" } },
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "geoip.location",
       "id": "3",
       "settings": { "precision": 3 },
       "type": "geohash_grid"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "logstash-http-* AND event_type:http",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-HTTP-AcceptEncoding",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "http.accept_encoding.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "logstash-http-* AND event_type:http",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-HTTP-AcceptEncodingByConnection",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "http.connection.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "http.accept_encoding.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "logstash-http-* AND event_type:http",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-HTTP-AcceptEncodingByConnection",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "http.user_agent.major.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "logstash-http-* AND event_type:http",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-HTTP-CacheControl",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "http.cache_control.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "logstash-http-* AND event_type:http",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-HTTP-UserAgentName",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "http.user_agent.name.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "logstash-http-* AND event_type:http",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-HTTP-Vary",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:11214",
       "fake": true,
       "field": "http.vary.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:11215",
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:11212",
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "logstash-http-* AND event_type:http",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-HTTP-ContentTypeByAplication",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "http.http_content_type.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "logstash-http-* AND event_type:http +http.http_content_type.keyword: application*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-HTTP-StatusCode",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "http.status",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "logstash-http-* AND event_type:http",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-HTTP-EventsOverTime",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "id": "6",
       "query": "*",
       "settings": {
        "filters": [
         { "label": "", "query": "event_type: http" }
        ]
       },
       "type": "filters"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "30m", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "logstash-http-* AND event_type:http",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-HTTP-UserAgentOS",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "http.user_agent.os.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "logstash-http-* AND event_type:http",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-HTTP-UserAgentDevices",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "http.user_agent.device.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "logstash-http-* AND event_type:http",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-HTTP-StatusCode",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "http.user_agent.os_name.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "logstash-http-* AND event_type:http",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-HTTP methods",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "http.http_method.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "100" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "logstash-http-* AND event_type:http",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-HTTP-Servers",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "http.server.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "logstash-http-* AND event_type:http",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-ThreatHunt-HTTP-PossibleC2Beacons-BySrcIP",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "http.length",
       "id": "9",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "100" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "src_ip.keyword",
       "id": "10",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "http.hostname.keyword",
       "id": "8",
       "settings": {
        "min_doc_count": "1",
        "missing": null,
        "order": "desc",
        "orderBy": "_term",
        "size": "20"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "alert.signature.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "logstash-http-* AND event_type:http NOT http.hostname.keyword: *\\.akadns.net NOT http.hostname.keyword: *\\.akamai.com NOT http.hostname.keyword: *\\.akamaihd.net NOT http.hostname.keyword: *\\.edgekey.net NOT http.hostname.keyword: *\\.akamai.net NOT http.hostname.keyword: *\\.akamaiedge.net NOT http.hostname.keyword: *\\.amazonaws.com NOT http.hostname.keyword: *\\.apple.com NOT http.hostname.keyword: *\\.apple-dns.net NOT http.hostname.keyword: *\\.icloud.com NOT http.hostname.keyword: *\\.in-addr.arpa NOT http.hostname.keyword: *\\.google.com NOT http.hostname.keyword: *\\.googlevideo.com NOT http.hostname.keyword: *\\.yahoo.com NOT http.hostname.keyword: *\\.linkedin.com NOT http.hostname.keyword: *\\.facebook.com NOT http.hostname.keyword: *\\.ntp.org NOT http.hostname.keyword: *\\.wikipedia.org NOT http.hostname.keyword: *\\.csdn.net NOT http.hostname.keyword: *\\.bing.com NOT http.hostname.keyword: *\\.instagram.com NOT http.hostname.keyword: *\\.twitter.com NOT http.hostname.keyword: *\\.microsoft.com NOT http.hostname.keyword: *\\.ebay.com NOT http.hostname.keyword: *\\.stackoverflow.com NOT http.hostname.keyword: *\\.whatsapp.com NOT http.hostname.keyword: *\\.live.com NOT http.hostname.keyword: *\\.reddit.com NOT http.hostname.keyword: *\\.netflix.com NOT http.hostname.keyword: *\\.alipay.com NOT http.hostname.keyword: *\\.office.com NOT http.hostname.keyword: *\\.office365.com NOT http.hostname.keyword: *\\.mcafee.com NOT http.hostname.keyword: *\\.windows.net NOT http.hostname.keyword: *\\.windows.com NOT http.hostname.keyword: *\\.msn.com NOT http.hostname.keyword: *\\.mozilla.com NOT http.hostname.keyword: *\\.mozilla.net NOT http.hostname.keyword: *\\.mozilla.org NOT http.hostname.keyword: *\\.spamhaus.org NOT http.hostname.keyword: *\\.wordpress.com NOT http.hostname.keyword: *\\.azure.com NOT http.hostname.keyword: *\\.digicert.com NOT http.hostname.keyword: *\\.trendmicro.com NOT http.hostname.keyword: *\\.onlinehome-server.info NOT http.hostname.keyword: *\\.gencloud.bg NOT http.hostname.keyword: *\\.avast.com NOT http.hostname.keyword: *\\.bitdefender.net",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-HTTP-EventsList",
   "type": "table",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select metric",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "select metric" }
       ],
       "settings": {},
       "type": "logs"
      }
     ],
     "query": "logstash-http-* AND event_type:http",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}