{
 "title": "SN-STATS",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "elasticsearch", "query": "elasticsearch" }
  ]
 },
 "panels": [
  {
   "title": "SN-Stats-KernelPacketsAndDrops-Deltas",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:12842",
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "30m", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:12838",
       "field": "stats.capture.kernel_drops_delta",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "$$hashKey": "object:12839",
       "field": "stats.capture.kernel_packets_delta",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "* event_type: stats",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-Stats-memuse-Deltas",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "30m", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "stats.dns.memuse_delta",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "stats.http.memuse_delta",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "stats.tcp.memuse_delta",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "stats.tcp.reassembly_memuse_delta",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "* event_type: stats",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-Stats-Memcap-Deltas",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "30m", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "stats.dns.memcap_global_delta",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "stats.dns.memcap_state_delta",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "stats.flow.memcap_delta",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "stats.http.memcap_delta",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "stats.tcp.segment_memcap_drop_delta",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "stats.tcp.ssn_memcap_drop_delta",
       "id": "8",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "* event_type: stats",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-Stats-CapturedPktsVsGaps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "30m", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "stats.capture.kernel_packets",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "stats.tcp.reassembly_gap",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "* event_type: stats",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-Stats-DecoderAvgMaxPktSize",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "30m", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "stats.decoder.avg_pkt_size",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "stats.decoder.max_pkt_size",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "* event_type: stats",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-Stats-DecoderBytes-Packets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "stats.decoder.bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "stats.decoder.pkts",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "* event_type:stats",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-Stats-TotalKernelPackets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "stats.capture.kernel_packets",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "* event_type:stats",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-Stats-DecoderProto-Deltas",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "30m", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "stats.decoder.erspan_delta",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "stats.decoder.ethernet_delta",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "stats.decoder.ethernet_delta",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "stats.decoder.ethernet_delta",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "stats.decoder.ethernet_delta",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "stats.decoder.ipv4_delta",
       "id": "8",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "stats.decoder.ipv4_in_ipv6_delta",
       "id": "9",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "stats.decoder.ipv6_delta",
       "id": "10",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "stats.decoder.ipv6_in_ipv6_delta",
       "id": "11",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "stats.decoder.mpls_delta",
       "id": "12",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "stats.decoder.ppp_delta",
       "id": "13",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "stats.decoder.pppoe_delta",
       "id": "14",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "stats.decoder.sctp_delta",
       "id": "15",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "stats.decoder.sll_delta",
       "id": "16",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "stats.decoder.tcp_delta",
       "id": "17",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "stats.decoder.udp_delta",
       "id": "18",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "stats.decoder.vlan_delta",
       "id": "19",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "stats.decoder.vlan_qinq_delta",
       "id": "20",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "* event_type: stats",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-Stats-EmergencyMode",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "30m", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "stats.flow.emerg_mode_entered",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "stats.flow.emerg_mode_over",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "* stats.flow.emerg_mode_entered and stats.flow.emerg_mode_over",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-Stats-ipv4-ipv6-fragments",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "30m", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "stats.defrag.ipv4.fragments",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "stats.defrag.ipv6.fragments",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "* event_type: stats",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-Stats-Frags",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "stats.defrag.ipv4.fragments",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "stats.defrag.ipv6.fragments",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "stats.defrag.max_frag_hits",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "* event_type: stats",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-Stats-Frags-Deltas",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "30m", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "stats.defrag.ipv4.fragments_delta",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "stats.defrag.ipv6.fragments_delta",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "stats.defrag.max_frag_hits_delta",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "* event_type: stats",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SN-STATS-EventsList",
   "type": "table",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select metric",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "select metric" }
       ],
       "settings": {},
       "type": "logs"
      }
     ],
     "query": "event_type:stats",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}